@startuml
class Supplier {
  - SupplierID: int
  - Name: string
  - Address: string
  - Email: string
  - Telephone: string
}

class Inventory {
  - ProductID: int
  - Name: string
  - Quantity: int
  - SupplierID: int
}
@enduml
